version: "3.8"

services:
  knowledge_api:
    restart: always
    build: .
    ports:
      - "8100:8100"
    volumes:
      - .:/app
    environment:
      - PORT=8100
      - NAME="Knowledge Database"
    depends_on:
      - qdrant

  qdrant:
    restart: always
    image: qdrant/qdrant
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
